server:
  # 配置端口号
  port: 8080

#配置日志文件
logging:
  config: classpath:log/log4j2.xml
  
#spring的配置
spring:
  #数据源配置
  datasource:
#    url: ${jdbc_url}
#    username: ${jdbc_username}
#    password: ${jdbc_password}
    url:  jdbc:mysql://127.0.0.1:3306/jtdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    # 使用druid数据源连接池
    type:  com.alibaba.druid.pool.DruidDataSource
    #加载驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  
  
#配置mybatis
mybatis:
  #一定要对应mapper映射xml文件的所在路径 
  mapper-locations: classpath:mapper/*/*.xml
  #实体类
  
# 配置beetl路径
beetl: 
  # 路径配置
  configPath: classpath:beetl/beetl.properties
  # 返回类型配置
  contentType: text/html;charset=UTF-8
  # 设置后缀
  suffix:
  
